import global_props from './GlobalProps';

const column_props = {
    "narrow": "is-narrow",

    "column": "column",
    "full": "is-full",
    "four-fifths": "is-four-fifths",
    "three-quarters": "is-three-quarters",
    "two-thirds": "is-two-thirds",
    "three-fifths": "is-three-fifths",
    "half": "is-half",
    "two-fifths": "is-two-fifths",
    "one-third": "is-one-third",
    "one-quarter": "is-one-quarter",
    "one-fifth": "is-one-fifth",
    "1": "is-1",
    "2": "is-2",
    "3": "is-3",
    "4": "is-4",
    "5": "is-5",
    "6": "is-6",
    "7": "is-7",
    "8": "is-8",
    "9": "is-9",
    "10": "is-10",
    "11": "is-11",
    "12": "is-12",
    "offset-full": "is-offset-full",
    "offset-four-fifths": "is-offset-four-fifths",
    "offset-three-quarters": "is-offset-three-quarters",
    "offset-two-thirds": "is-offset-two-thirds",
    "offset-three-fifths": "is-offset-three-fifths",
    "offset-half": "is-offset-half",
    "offset-two-fifths": "is-offset-two-fifths",
    "offset-one-third": "is-offset-one-third",
    "offset-one-quarter": "is-offset-one-quarter",
    "offset-one-fifth": "is-offset-one-fifth",
    "offset-1": "is-offset-1",
    "offset-2": "is-offset-2",
    "offset-3": "is-offset-3",
    "offset-4": "is-offset-4",
    "offset-5": "is-offset-5",
    "offset-6": "is-offset-6",
    "offset-7": "is-offset-7",
    "offset-8": "is-offset-8",
    "offset-9": "is-offset-9",
    "offset-10": "is-offset-10",
    "offset-11": "is-offset-11",
    "offset-12": "is-offset-12",
}

export default { ...column_props, ...global_props };